language: ruby
before_install:
  # jruby-head does not have bundler.
  - which bundle || gem install bundler
script: spec/run
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
  - ruby-head
  - ree
  - jruby-18mode
  - jruby
  - jruby-head
  - rbx
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS='--2.0'
  allow_failures:
    - rvm: rbx
  fast_finish: true
