language: ruby
bundler_args: "--binstubs --standalone --without documentation"
script: bundle exec rspec
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - ree
  - jruby-18mode
  - jruby
  - jruby-head
  - rbx


script: "script/run_build"
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS='--2.0'
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx
  fast_finish: true
